import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quiet Geek</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>Hellooooooo !!!</div>
    </div>
  )
}
